// <auto-generated />
namespace SetLight.AccesoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Sync_UnitRentalPrice_Manual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sync_UnitRentalPrice_Manual));
        
        string IMigrationMetadata.Id
        {
            get { return "202512172124257_Sync_UnitRentalPrice_Manual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
