// <auto-generated />
namespace SetLight.AccesoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Sync_Maintenance_IdEmpleado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sync_Maintenance_IdEmpleado));
        
        string IMigrationMetadata.Id
        {
            get { return "202511151904010_Sync_Maintenance_IdEmpleado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
